CREATE TABLE categorias
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categorias PRIMARY KEY (id)
);

CREATE TABLE sala_letras
(
    sala_id BIGINT       NOT NULL,
    letras  VARCHAR(255) NOT NULL
);

CREATE TABLE salas
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rodadas          INTEGER                                 NOT NULL,
    maximo_jogadores INTEGER                                 NOT NULL,
    senha            VARCHAR(255),
    tempo_jogo       VARCHAR(255)                            NOT NULL,
    privada          BOOLEAN                                 NOT NULL,
    versao           INTEGER,
    CONSTRAINT pk_salas PRIMARY KEY (id)
);

CREATE TABLE salas_categorias
(
    sala_id       BIGINT NOT NULL,
    categorias_id BIGINT NOT NULL
);

CREATE TABLE usuarios
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome    VARCHAR(255),
    nota    INTEGER,
    sala_id BIGINT,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE categorias
    ADD CONSTRAINT uc_categorias_nome UNIQUE (nome);

ALTER TABLE usuarios
    ADD CONSTRAINT FK_USUARIOS_ON_SALA FOREIGN KEY (sala_id) REFERENCES salas (id);

ALTER TABLE sala_letras
    ADD CONSTRAINT fk_sala_letras_on_sala FOREIGN KEY (sala_id) REFERENCES salas (id);

ALTER TABLE salas_categorias
    ADD CONSTRAINT fk_salcat_on_categoria FOREIGN KEY (categorias_id) REFERENCES categorias (id);

ALTER TABLE salas_categorias
    ADD CONSTRAINT fk_salcat_on_sala FOREIGN KEY (sala_id) REFERENCES salas (id);