CREATE TABLE resposta_respostas_informadas
(
    resposta_id BIGINT       NOT NULL,
    resposta    VARCHAR(255),
    categoria   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_resposta_respostasinformadas PRIMARY KEY (resposta_id, categoria)
);

CREATE TABLE respostas
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sala_id    BIGINT,
    usuario_id BIGINT,
    CONSTRAINT pk_respostas PRIMARY KEY (id)
);

ALTER TABLE respostas
    ADD CONSTRAINT FK_RESPOSTAS_ON_SALA FOREIGN KEY (sala_id) REFERENCES salas (id);

ALTER TABLE respostas
    ADD CONSTRAINT FK_RESPOSTAS_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuarios (id);

ALTER TABLE resposta_respostas_informadas
    ADD CONSTRAINT fk_resposta_respostasinformadas_on_resposta FOREIGN KEY (resposta_id) REFERENCES respostas (id);
